--liquibase formatted sql

--changeset vladimirsa:001-create-users
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    phone VARCHAR(50),
    role VARCHAR(50) NOT NULL,
    image VARCHAR(255)
);

--changeset vladimirsa:002-unique-users-email
CREATE UNIQUE INDEX ux_users_email ON users(email);

--changeset vladimirsa:003-create-ads
CREATE TABLE ads (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price INT NOT NULL,
    image VARCHAR(255),
    author_id INT NOT NULL,
    CONSTRAINT fk_ads_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

--changeset vladimirsa:004-index-ads-author
CREATE INDEX idx_ads_author_id ON ads(author_id);

--changeset vladimirsa:005-create-comments
CREATE TABLE comments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    ad_id INT NOT NULL,
    author_id INT NOT NULL,
    CONSTRAINT fk_comments_ad FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

--changeset vladimirsa:006-index-comments-ad
CREATE INDEX idx_comments_ad_id ON comments(ad_id);

--changeset vladimirsa:007-index-comments-author
CREATE INDEX idx_comments_author_id ON comments(author_id);

--changeset vladimirsa:008-create-hibernate-sequence
CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

--changeset vladimirsa:009-create-images
CREATE TABLE images (
    id VARCHAR(100) PRIMARY KEY,
    data BYTEA NOT NULL,
    content_type VARCHAR(120),
    size BIGINT
);

--changeset vladimirsa:010-alter-images-add-metadata
ALTER TABLE images ALTER COLUMN data DROP NOT NULL;
ALTER TABLE images ADD COLUMN created_at BIGINT;
ALTER TABLE images ADD COLUMN checksum VARCHAR(64);

--changeset vladimirsa:011-add-image-id-columns
ALTER TABLE ads ADD COLUMN image_id VARCHAR(100);
ALTER TABLE users ADD COLUMN image_id VARCHAR(100);
ALTER TABLE ads ADD CONSTRAINT fk_ads_image FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE SET NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_image FOREIGN KEY (image_id) REFERENCES images(id) ON DELETE SET NULL;

--changeset vladimirsa:012-drop-old-image-columns
ALTER TABLE ads DROP COLUMN image;
ALTER TABLE users DROP COLUMN image;

--changeset vladimirsa:014-drop-unused-image-columns
ALTER TABLE images DROP COLUMN IF EXISTS data;
ALTER TABLE images DROP COLUMN IF EXISTS checksum;
